language: node_js
os: osx
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - yarn install
script:
  - yarn tests
