language: node_js
node_js:
  - "9"
sudo: required
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
